server:
  port: 5000

spring:   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernet:
       dialect: org.hibernate.dialect.MariaDBDialect
       
learning:
     aws:
      access_key: 
      secret_key: 
             
                        